#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "Creating python virtual environment..."
python3 -m venv .venv

echo "Installing requirements..."
.venv/bin/python -m pip install --upgrade pip
.venv/bin/python -m pip install --requirement requirements.txt

echo "Installing pre-commit hooks..."
.venv/bin/pre-commit install
