send_magic_packet:
  fields:
    mac:
      required: true
      example: "00:01:02:03:04:05"
      selector:
        text:
    broadcast_address:
      required: false
      example: "255.255.255.255"
      selector:
        text:
    broadcast_port:
      required: false
      example: 9
      selector:
        number:
